BaCa2/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from main.views import BaCa2LoginView, BaCa2LogoutView, LoginRedirectView
from util.views import FieldValidationView

urlpatterns = [
    path('baca/', admin.site.urls),

    # ------------------------------------- Authentication ------------------------------------- #
    path('', LoginRedirectView.as_view(), name='login-redirect'),
    path('login/', BaCa2LoginView.as_view(), name='login'),
    path('logout/', BaCa2LogoutView.as_view(), name='logout'),

    path('oidc/', include('mozilla_django_oidc.urls')),

    # ------------------------------------------ Apps ------------------------------------------ #
    path('broker_api/', include('broker_api.urls')),
    path('main/', include('main.urls')),
    path('course/<int:course_id>/', include('course.urls')),

    # --------------------------------------- Auxiliary ---------------------------------------- #
    path('field_validation', FieldValidationView.as_view(), name='field-validation'),
]

if settings.MEDIA_OFFLINE_SERVING:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BaCa2/main/urls.py
from django.urls import path

from .views import (
    AdminView,
    AnnouncementEditView,
    AnnouncementModelView,
    CourseModelView,
    CoursesView,
    DashboardView,
    DevelopmentTimelineView,
    PermissionModelView,
    ProfileView,
    RoleModelView,
    RoleView,
    TestView,
    UserModelView,
    change_password,
    change_theme
)

app_name = 'main'

urlpatterns = [
    # -------------------------------------- Model views --------------------------------------- #
    path('models/course/', CourseModelView.as_view(), name='course-model-view'),
    path('models/user/', UserModelView.as_view(), name='user-model-view'),
    path('models/role/', RoleModelView.as_view(), name='role-model-view'),
    path('models/permission/', PermissionModelView.as_view(), name='permission-model-view'),
    path('models/announcement/', AnnouncementModelView.as_view(), name='announcement-model-view'),

    # --------------------------------------- Main views --------------------------------------- #
    path('admin/', AdminView.as_view(), name='admin'),
    path('announcement/<int:announcement_id>/', AnnouncementEditView.as_view(),
         name='announcement-edit'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('dev_timeline/', DevelopmentTimelineView.as_view(), name='dev-timeline'),
    path('courses/', CoursesView.as_view(), name='courses'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('role/<int:role_id>/', RoleView.as_view(), name='role'),

    path('change_theme', change_theme, name='change-theme'),
    path('change_password', change_password, name='change-password'),

    path('test/', TestView.as_view(), name='test'),
]

BaCa2/templates/widget_templates/navigation/navbar.html
{% load static %}

<nav class="navbar navbar-expand-md fixed-top">
    <div class="container">
        <a class="navbar-brand me-4" href="{% url 'main:dashboard' %}">
            <div class="logo-wrapper logo-horizontal logo-xs">
                {% include 'util/baca2_logo.html' %}
            </div>
        </a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#collapsible"
                aria-controls="collapsible"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="collapsible">
            <ul class="navbar-nav me-auto links">
                {% for link in navbar_widget.links %}
                    {% if link == '|' %}
                        <li class="ms-2 me-3 nav-divider"></li>
                    {% else %}
                        <li class="nav-item me-2
                                   {% if request.path == link.url %} active {% endif %}">
                            <a class="nav-link hover-underline"
                               href="{{ link.url }}">{{ link.name }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <div class="d-flex nav-link hover-highlight">
                        {% include 'util/theme_button.html' %}
                    </div>
                </li>
                {% comment %}<li class="nav-item">
                    <!-- TODO -->
                    <a class="nav-link hover-highlight" href="#">
                        <div class="icon-wrapper icon-m d-flex">
                            {% include 'icons/bell.svg' %}
                        </div>
                    </a>
                </li>{% endcomment %}
                <li class="nav-item dropdown">
                    <!-- TODO -->
                    <a class="nav-link dropdown-toggle hover-highlight"
                       href="#"
                       id="user-links"
                       data-bs-toggle="dropdown">
                        <div class="icon-wrapper icon-m d-flex">
                            {% include 'icons/user.svg' %}
                        </div>
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'main:profile' %}">Profil</a>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <a class="dropdown-item" href="{% url 'logout' %}">Wyloguj</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

BaCa2/templates/widget_templates/navigation/sidenav.html
<div class="col-lg-3 col-md-4 col-12 {{ sidenav.widget_class }}" id="{{ sidenav.name }}">
    <ul class="sidenav-tabs">
        {% for tab in sidenav.tabs %}
            {% include 'widget_templates/navigation/sidenav_tab.html' %}
        {% endfor %}
    </ul>
</div>

BaCa2/templates/widget_templates/navigation/sidenav_tab.html
<li class="{{ tab.widget_class }}" id="{{ tab.name }}">
    <div class="tab-header">
        {% if tab.icon %}
            <div class="tab-icon">
                <i class="bi bi-{{ tab.icon }}"></i>
            </div>
        {% endif %}
        <div class="tab-text">
            <div class="tab-title">
                {{ tab.title }}
            </div>
            {% if tab.hint_text %}
                <div class="tab-hint">
                    {{ tab.hint_text }}
                </div>
            {% endif %}
        </div>
        {% if tab.sub_tabs %}
            <div class="tab-arrow">
                <i class="bi bi-chevron-right"></i>
            </div>
        {% endif %}
    </div>
    {% if tab.sub_tabs %}
        <div class="sub-tabs-wrapper">
            <ul class="sub-tabs">
                {% for sub_tab in tab.sub_tabs %}
                    {% with sub_tab as tab %}
                        {% include 'widget_templates/navigation/sidenav_tab.html' %}
                    {% endwith %}
                {% endfor %}
                <div class="sub-tabs-spacer"></div>
            </ul>
        </div>
    {% endif %}
</li>