BaCa2/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from main.views import BaCa2LoginView, BaCa2LogoutView, LoginRedirectView
from util.views import FieldValidationView

urlpatterns = [
    path('baca/', admin.site.urls),

    # ------------------------------------- Authentication ------------------------------------- #
    path('', LoginRedirectView.as_view(), name='login-redirect'),
    path('login/', BaCa2LoginView.as_view(), name='login'),
    path('logout/', BaCa2LogoutView.as_view(), name='logout'),

    path('oidc/', include('mozilla_django_oidc.urls')),

    # ------------------------------------------ Apps ------------------------------------------ #
    path('broker_api/', include('broker_api.urls')),
    path('main/', include('main.urls')),
    path('course/<int:course_id>/', include('course.urls')),

    # --------------------------------------- Auxiliary ---------------------------------------- #
    path('field_validation', FieldValidationView.as_view(), name='field-validation'),
]

if settings.MEDIA_OFFLINE_SERVING:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BaCa2/main/urls.py
from django.urls import path

from .views import (
    AdminView,
    AnnouncementEditView,
    AnnouncementModelView,
    CourseModelView,
    CoursesView,
    DashboardView,
    DevelopmentTimelineView,
    PermissionModelView,
    ProfileView,
    RoleModelView,
    RoleView,
    TestView,
    UserModelView,
    change_password,
    change_theme
)

app_name = 'main'

urlpatterns = [
    # -------------------------------------- Model views --------------------------------------- #
    path('models/course/', CourseModelView.as_view(), name='course-model-view'),
    path('models/user/', UserModelView.as_view(), name='user-model-view'),
    path('models/role/', RoleModelView.as_view(), name='role-model-view'),
    path('models/permission/', PermissionModelView.as_view(), name='permission-model-view'),
    path('models/announcement/', AnnouncementModelView.as_view(), name='announcement-model-view'),

    # --------------------------------------- Main views --------------------------------------- #
    path('admin/', AdminView.as_view(), name='admin'),
    path('announcement/<int:announcement_id>/', AnnouncementEditView.as_view(),
         name='announcement-edit'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('dev_timeline/', DevelopmentTimelineView.as_view(), name='dev-timeline'),
    path('courses/', CoursesView.as_view(), name='courses'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('role/<int:role_id>/', RoleView.as_view(), name='role'),

    path('change_theme', change_theme, name='change-theme'),
    path('change_password', change_password, name='change-password'),

    path('test/', TestView.as_view(), name='test'),
]

BaCa2/templates/widget_templates/announcement.html
<div class="card announcement {{ announcement.widdget_class }}"
     id="{{ announcement.name }}">
    <div class="card-header">
        <div class="row align-items-center">
            <div class="col-auto">
                <h5 class="card-title">{{ announcement.title }}</h5>
            </div>
            {% if announcement.display_date %}
                <div class="col d-flex justify-content-end text-muted">
                    {{ announcement.date }}
                </div>
            {% endif %}
        </div>
    </div>
    <div class="card-body">
        <div class="card-text">
            {{ announcement.content|safe }}
        </div>
    </div>
</div>

BaCa2/templates/widget_templates/announcement_block.html
<div class="announcement-block {{ annonucement_block.widget_class }} scrollable"
     id="{{ annonucement_block.name }}">
    {% for announcement in announcement_block.announcements %}
        <div class="announcement-wrapper">
            {% include 'widget_templates/announcement.html' %}
        </div>
    {% endfor %}
</div>

BaCa2/templates/widget_templates/attachment.html
{% load static %}

<a {% if attachment.source_type == 'page' %} href="{{ attachment.link }}"
{% else %} href="{{ attachment.link }}" download="{{ attachment.download_name }}" {% endif %}
   id="{{ attachment.name }}"
   class="{{ attachment.widget_class }}">
    <i class="bi bi-{{ attachment.icon }} me-1"></i> {{ attachment.title }}
</a>

BaCa2/templates/widget_templates/brief_result_summary.html
{% load static %}
{% load i18n %}

<div class="card mb-3 test-summary" id="{{ brief_result_summary.name }}">
    <div class="card-header">
        <h5 class="card-title mb-0">{{ brief_result_summary.set_name }}/{{ brief_result_summary.test_name }}</h5>
    </div>
    <div class="card-body">
        <div class="container text-center">
            <div class="row">
                <div class="col col-auto d-flex result-status
                            {{ brief_result_summary.result.status }}">
                    <b class="me-1">{% trans "Status:" %}</b>
                    {{ brief_result_summary.result.f_status }}
                </div>
                {% if brief_result_summary.result.f_time_real %}
                    <div class="col result-time {{ brief_result_summary.result.status }}">
                        <b class="me-1">{% trans "Time used:" %}</b>
                        {{ brief_result_summary.result.f_time_real }}
                    </div>
                {% endif %}
                {% if brief_result_summary.result.f_runtime_memory %}
                    <div class="col col-auto d-flex result-memory
                                {{ brief_result_summary.result.status }}">
                        <b class="me-1">{% trans "Memory used:" %}</b>
                        {{ brief_result_summary.result.f_runtime_memory }}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    {% with brief_result_summary.result as result %}
        {% if result.logs_present %}
            <ul class="nav nav-tabs compile-tabs-nav" role="tablist">
                <li class="nav-item" role="presentation">
                    <button class="nav-link {% if result.compile_log_widget %} active {% endif %} ms-2"
                            id="{{ brief_result_summary.name }}-compile-tab-btn"
                            data-bs-toggle="tab"
                            data-bs-target="#{{ brief_result_summary.name }}-compile-tab"
                            type="button"
                            role="tab"
                            {% if not result.compile_log_widget %} disabled {% endif %}>
                        {% trans "Compile logs" %}
                    </button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link
                            {% if not result.compile_log_widget and not result.multiple_logs %}
                                active
                            {% endif %}"
                            id="{{ brief_result_summary.name }}-checker-tab-btn"
                            data-bs-toggle="tab"
                            data-bs-target="#{{ brief_result_summary.name }}-checker-tab"
                            type="button"
                            role="tab"
                            {% if not result.checker_log_widget %} disabled {% endif %}>
                        {% trans "Checker logs" %}
                    </button>
                </li>
            </ul>

            <div class="tab-content compile-tabs">

                {% if result.compile_log_widget %}
                    <div class="tab-pane fade
                                {% if result.compile_log_widget %} show active {% endif %}"
                         id="{{ brief_result_summary.name }}-compile-tab"
                         role="tabpanel">
                        {% with result.compile_log_widget as codeblock %}
                            {% include "widget_templates/code_block.html" %}
                        {% endwith %}
                    </div>
                {% endif %}

                {% if result.checker_log_widget %}
                    <div class="tab-pane fade
                                {% if not result.compile_log_widget and not result.multiple_logs %}
                                    show active
                                {% endif %}"
                         id="{{ brief_result_summary.name }}-checker-tab"
                         role="tabpanel">
                        {% with result.checker_log_widget as codeblock %}
                            {% include "widget_templates/code_block.html" %}
                        {% endwith %}
                    </div>
                {% endif %}

            </div>
        {% endif %}
    {% endwith %}
    </div>

BaCa2/templates/widget_templates/code_block.html
{% if codeblock.display_wrapper %}
    <div class="code-block-wrapper card">
    {% if codeblock.title %}
        <div class="card-header">
            <h5 class="card-title mb-0">{{ codeblock.title }}</h5>
        </div>
    {% endif %}
    <div class="card-body p-0">
{% endif %}
<pre class="{{ codeblock.widget_class }}"
     id="{{ codeblock.name }}"
     remove-initial-line-feed="true">
        <code class="language-{{ codeblock.language }}">
            {{ codeblock.code }}
        </code>
</pre>
{% if codeblock.display_wrapper %}
    </div>
    </div>
{% endif %}

BaCa2/templates/widget_templates/form_base.html
{% load static %}
<script src="{% static 'js/forms.js' %}"></script>

<form method="post">
    {% csrf_token %}

    {% if form_widget.display_non_field_errors %}
        {% if form_widget.form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form_widget.form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
    {% endif %}

    {% block form_fields %}
    {% endblock %}

    <div class="form-footer">
        <button type="submit" class="btn btn-primary w-100">
            {{ form_widget.button_text }}
        </button>
    </div>
</form>

BaCa2/templates/widget_templates/form_field.html
{% load widget_tweaks %}
{% load custom_tags %}

<div class="input-block mb-3">
    <div class="input-group
            {% if field.name in form_widget.toggleable_fields %}
                toggleable
                {% if field.value %}
                    toggleable-on
                {% else %}
                    toggleable-off
                {% endif %}
            {% endif %}">
        {% if form_widget.floating_labels %}
            <div class="form-floating">
        {% else %}
            <label for="{{ field.name }}" class="form-label">{{ field.label }}</label>
        {% endif %}

        {% if form_widget.display_field_errors and form_widget.form.is_bound %}
            {% if field.errors %}
                {% render_field field class="form-control is-invalid" id=field.name placeholder="-" %}
            {% else %}
                {% render_field field class="form-control is-valid" id=field.name placeholder="-" %}
            {% endif %}
        {% else %}
            {% render_field field class="form-control" id=field.name placeholder="-" %}
        {% endif %}

        {% if form_widget.floating_labels %}
            <label for="{{ field.name }}" class="form-label">{{ field.label }}</label>
            </div>
        {% endif %}

        {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}

        {% if field.name in form_widget.toggleable_fields %}
            {% with button_params=form_widget.toggleable_fields_params|get_item:field.name %}
                <button class="btn btn-outline-secondary"
                        type="button"
                        onclick="toggleField('{{ field.name }}',
                                '{{ button_params|get_item:'button_text_off' }}',
                                '{{ button_params|get_item:'button_text_on' }}')">
                    {% if field.value %}
                        {{ button_params|get_item:'button_text_on'}}
                    {% else %}
                        {{ button_params|get_item:'button_text_off'}}
                    {% endif %}
                </button>
            {% endwith %}
        {% endif %}
    </div>

    {% if form_widget.display_field_errors and form_widget.form.is_bound %}
        {% if field.errors %}
            {% for error in field.errors %}
                <div class="invalid-feedback">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}
    {% endif %}
</div>

{% if form_widget.live_validation and field.field.widget.input_type != "password" %}
    <script>
        $(document).ready( function () {
            $('#{{ field.name }}').on('input', function () {
                update_validation_status(
                    this,
                    '{{ form_widget.field_classes|get_item:field.name }}',
                    '{{ form_widget.field_required|get_item:field.name }}',
                    '{{ form_widget.field_min_length|get_item:field.name }}',
                    '{% url 'main:field-validation' %}');
            });
        });
    </script>
{% endif %}

BaCa2/templates/widget_templates/markup_displayer.html
{% load static %}
{% load i18n %}

<style>
    #{{ displayer.name }} {
        line-height: {{ displayer.line_height }};
        overflow-y: auto;
    }

    {% if displayer.limit_display_height %}
        #{{ displayer.name }} {
            max-height: {{ displayer.display_height }};
        }
    {% endif %}
</style>

<div id="{{ displayer.name }}" class="card markup-display">
    {% if displayer.pdf_download %}
        <div class="card-header">
            <a href="{{ displayer.pdf_download }}"
               download="{{ displayer.pdf_download_name }}"
               class="btn btn-sm btn-outline-light_muted">
                <i class="bi bi-download"></i> {% trans "Download PDF" %}
            </a>
        </div>
    {% endif %}
    <div class="card-body">
        {{ displayer.content|safe }}
    </div>
</div>

BaCa2/templates/widget_templates/pdf_displayer.html
{% load static %}
{% load i18n %}

<div class="pdf-displayer card" id="{{ displayer.name }}">
    <div class="card-header">
        <div class="row align-items-center">
            <div class="col">
                <a href="{{ displayer.file_path }}"
                   download="{{ displayer.download_name }}"
                   class="btn btn-sm btn-outline-light_muted">
                    <i class="bi bi-download"></i> {% trans "Download" %}
                </a>
            </div>
            <div class="col">
                <div class="pdf-navigation row align-items-center justify-content-end">
                    <div class="col-auto pe-1">
                        <button class="prev-page-btn btn btn-sm btn-outline-light_muted">
                            <i class="bi bi-caret-left"></i>
                        </button>
                    </div>
                    <div class="col-auto ps-1">
                        <button class="next-page-btn btn btn-sm btn-outline-light_muted">
                            <i class="bi bi-caret-right"></i>
                        </button>
                    </div>
                    <div class="col-auto d-flex align-items-center ps-1">
                        <div class="pdf-page-info">
                                <p class="m-0">{% trans "Page" %}</p>
                                <form class="pdf-page-change">
                                    <div class="input-group input-group-sm ms-2 me-2">
                                        <input class="form-control pdf-page-number" value="1">
                                    </div>
                                </form>
                                <p class="m-0">{% trans "of" %}</p>
                                <span class="ms-2 pdf-page-count">1</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body">
        <canvas style="width: 100%"></canvas>
    </div>
</div>

<script>
    let url = '{{ displayer.file_path }}';
    new PDFDisplayer('{{ displayer.name }}', url);
</script>

BaCa2/templates/widget_templates/text_displayer.html
{% if displayer.displayer_type == 'markup' %}
    {% with displayer.displayer as displayer %}
        {% include 'widget_templates/markup_displayer.html' %}
    {% endwith %}
{% elif displayer.displayer_type == 'pdf' %}
    {% with displayer.displayer as displayer %}
        {% include 'widget_templates/pdf_displayer.html' %}
    {% endwith %}
{% else %}
    {{ displayer.displayer.message }}
{% endif %}