BaCa2/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from main.views import BaCa2LoginView, BaCa2LogoutView, LoginRedirectView
from util.views import FieldValidationView

urlpatterns = [
    path('baca/', admin.site.urls),

    # ------------------------------------- Authentication ------------------------------------- #
    path('', LoginRedirectView.as_view(), name='login-redirect'),
    path('login/', BaCa2LoginView.as_view(), name='login'),
    path('logout/', BaCa2LogoutView.as_view(), name='logout'),

    path('oidc/', include('mozilla_django_oidc.urls')),

    # ------------------------------------------ Apps ------------------------------------------ #
    path('broker_api/', include('broker_api.urls')),
    path('main/', include('main.urls')),
    path('course/<int:course_id>/', include('course.urls')),

    # --------------------------------------- Auxiliary ---------------------------------------- #
    path('field_validation', FieldValidationView.as_view(), name='field-validation'),
]

if settings.MEDIA_OFFLINE_SERVING:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BaCa2/main/urls.py
from django.urls import path

from .views import (
    AdminView,
    AnnouncementEditView,
    AnnouncementModelView,
    CourseModelView,
    CoursesView,
    DashboardView,
    DevelopmentTimelineView,
    PermissionModelView,
    ProfileView,
    RoleModelView,
    RoleView,
    TestView,
    UserModelView,
    change_password,
    change_theme
)

app_name = 'main'

urlpatterns = [
    # -------------------------------------- Model views --------------------------------------- #
    path('models/course/', CourseModelView.as_view(), name='course-model-view'),
    path('models/user/', UserModelView.as_view(), name='user-model-view'),
    path('models/role/', RoleModelView.as_view(), name='role-model-view'),
    path('models/permission/', PermissionModelView.as_view(), name='permission-model-view'),
    path('models/announcement/', AnnouncementModelView.as_view(), name='announcement-model-view'),

    # --------------------------------------- Main views --------------------------------------- #
    path('admin/', AdminView.as_view(), name='admin'),
    path('announcement/<int:announcement_id>/', AnnouncementEditView.as_view(),
         name='announcement-edit'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('dev_timeline/', DevelopmentTimelineView.as_view(), name='dev-timeline'),
    path('courses/', CoursesView.as_view(), name='courses'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('role/<int:role_id>/', RoleView.as_view(), name='role'),

    path('change_theme', change_theme, name='change-theme'),
    path('change_password', change_password, name='change-password'),

    path('test/', TestView.as_view(), name='test'),
]

BaCa2/util/models.py
from importlib import import_module
from typing import Dict, List, Type, TypeVar, Union

from django.contrib.auth.models import ContentType, Group, Permission
from django.db import models
from django.db.models.query import QuerySet

from core.choices import BasicModelAction

model_cls = TypeVar('model_cls', bound=Type[models.Model])


def get_all_permissions_for_model(model: model_cls) -> Union[QuerySet, List[Permission]]:
    """
    Returns all permissions for given model.

    :param model: Model to get permissions for.
    :type model: Type[models.Model]

    :return: List of permissions for given model.
    :rtype: QuerySet[Permission]
    """
    return Permission.objects.filter(
        content_type=ContentType.objects.get_for_model(model).id
    )


def get_all_models_from_app(app_label: str) -> Dict[str, model_cls]:
    """
    Returns all models from given app. App has to have the `__all__` variable defined in models.py.

    :param app_label: Name of the app.
    :type app_label: str

    :return: Dictionary of models from given app. Keys are model names, values are model classes.
    :rtype: Dict[str, Type[models.Model]]
    """
    module = import_module(f'{app_label}.models')
    return {model: getattr(module, model) for model in module.__all__}


def get_model_permission_by_label(model: model_cls, perm_label: str) -> Permission:
    """
    Returns permission object for a given model and permission label.

    :param model: Model to get permission for.
    :type model: Type[models.Model]
    :param perm_label: Permission label (e.g. 'add', 'change', 'view', 'delete').
    :type perm_label: str

    :return: Permission object with codename equal to '`label`' + '_' + '`model name`'.
    :rtype: Permission
    """
    return Permission.objects.get(codename=f'{perm_label}_{model._meta.model_name}')


def get_model_permissions(
        model: model_cls,
        permissions: BasicModelAction | List[BasicModelAction] = 'all'
) -> QuerySet[Permission]:
    """
    Returns QuerySet of basic permissions objects for given model. If permissions is set to 'all'
    (default), all basic permissions for given model are returned, otherwise only specified
    permissions are returned.

    Basic permissions are the permissions automatically created by Django for each model (add,
    change, view, delete).

    :param model: Model to get permissions for.
    :type model: Type[models.Model]
    :param permissions: List of permissions to get. If set to 'all' (default), all basic permissions
        are returned. Can be set to a list of BasicPermissionAction or a single BasicModelAction.
    :type permissions: BasicModelAction | List[BasicPermissionType]

    :return: QuerySet of basic permissions for given model.
    :rtype: QuerySet[Permission]
    """
    if permissions == 'all':
        permissions = [p for p in BasicModelAction]
    elif isinstance(permissions, BasicModelAction):
        permissions = [f'{permissions.label}_{model._meta.model_name}']
    elif isinstance(permissions, List):
        permissions = [f'{p.label}_{model._meta.model_name}' for p in permissions]

    return Permission.objects.filter(codename__in=permissions)


def delete_populated_group(group: Group) -> None:
    """
    Deletes a group along with all its user and permission assignments (does not delete the users or
    permissions themselves).

    :param group: Group to delete.
    :type group: Group
    """

    group.user_set.clear()
    group.permissions.clear()
    group.delete(using='default')


def delete_populated_groups(groups: List[Group]) -> None:
    """
    Deletes a list of groups along with all their user and permission assignments (does not
    delete the users or permissions themselves).

    :param groups: List of groups to delete.
    :type groups: List[Group]
    """

    for group in groups:
        delete_populated_group(group)

BaCa2/util/views.py
from abc import ABC
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Type

import django.db.models
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import TemplateView

from core.choices import BasicModelAction
from util import (
    add_kwargs_to_url,
    decode_url_to_dict,
    encode_dict_to_url,
    normalize_string_to_python
)
from util.models import model_cls
from util.responses import BaCa2JsonResponse, BaCa2ModelResponse
from widgets.base import Widget
from widgets.brief_result_summary import BriefResultSummary
from widgets.code_block import CodeBlock
from widgets.forms import FormWidget
from widgets.forms.fields.validation import get_field_validation_status
from widgets.listing import TableWidget, Timeline
from widgets.navigation import NavBar, Sidenav
from widgets.notification import Announcement, AnnouncementBlock
from widgets.text_display import MarkupDisplayer, PDFDisplayer, TextDisplayer


class BaCa2ContextMixin:
    """
    Context mixin for all BaCa2 views used to establish shared context dictionary structure and
    context gathering logic between different views. Provides a preliminary setup for the context
    dictionary and a method for adding widgets to it. The :py:meth:`get_context_data` method of
    this mixin calls on the :py:meth:`get_context_data` method of the other following ancestor in
    the MRO chain and as such it should precede in the parent list of the view class any other mixin
    or view which calls on that method.
    """

    class WidgetException(Exception):
        """
        Exception raised when widget-related error occurs.
        """
        pass

    #: List of all widget types used in BaCa2 views.
    WIDGET_TYPES = [
        FormWidget,
        NavBar,
        Sidenav,
        TableWidget,
        TextDisplayer,
        MarkupDisplayer,
        PDFDisplayer,
        CodeBlock,
        BriefResultSummary,
        Timeline,
        Announcement,
        AnnouncementBlock
    ]
    #: List of all widgets which are unique (i.e. there can only be one instance of each widget type
    #: can exist in the context dictionary).
    UNIQUE_WIDGETS = [NavBar, Sidenav]
    #: Default theme for users who are not logged in.
    DEFAULT_THEME = 'dark'

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        """
        Returns a dictionary containing all the data required by the template to render the view.
        Calls on the `get_context_data` method of the other following ancestor (should there be
        one) in the MRO chain (As such, if this mixin precedes in the parent list of the view
        class an ancestor view whose context gathering is also necessary, it is enough to call on
        the `get_context_data` once through the super() method).

        :param kwargs: Keyword arguments passed to the `get_context_data` method of the other
            following ancestor in the MRO chain (should there be one).
        :type kwargs: dict

        :return: A dictionary containing data required by the template to render the view.
        :rtype: Dict[str, Any]

        :raises Exception: If no request object is found.
        """
        super_context = getattr(super(), 'get_context_data', None)
        if super_context and callable(super_context):
            context = super_context(**kwargs)
        else:
            context = {}

        context['widgets'] = {widget_type.__name__: {} for widget_type in
                              BaCa2ContextMixin.WIDGET_TYPES}

        request = getattr(self, 'request', None)
        if request:
            if request.user.is_authenticated:
                context['data_bs_theme'] = request.user.user_settings.theme
                context['display_navbar'] = True
                self.add_widget(context, NavBar(request))
            else:
                context['data_bs_theme'] = BaCa2ContextMixin.DEFAULT_THEME
                context['display_navbar'] = False
        else:
            raise Exception('No request object found. Remember that BaCa2ContextMixin should only '
                            'be used as a view mixin.')

        context['display_sidenav'] = False
        context['page_title'] = 'BaCa²'
        context['request'] = request

        return context

    @staticmethod
    def add_widget(context: Dict[str, Any], widget: Widget) -> None:
        """
        Add a widget to the context dictionary. The widget is added to its corresponding widget
        type dictionary (in the `widgets` dictionary of the main context dict) under its name as a
        key.

        :param context: Context dictionary to which the widget is to be added.
        :type context: Dict[str, Any]

        :param widget: Widget to be added to the context dictionary.
        :type widget: Widget

        :raises WidgetException: If the widget type is not recognized or if it is unique and
            already exists in the context dictionary.
        """
        widget_type = BaCa2ContextMixin.get_type(type(widget))

        if not widget_type:
            raise BaCa2ContextMixin.WidgetException(f'Widget type not recognized: {widget_type}.')

        if all((BaCa2ContextMixin.has_widget_type(context, widget_type),
                widget_type in BaCa2ContextMixin.UNIQUE_WIDGETS)):
            raise BaCa2ContextMixin.WidgetException(f'Widget of type {widget_type} already '
                                                    f'exists in the context dictionary.')

        if widget_type == Sidenav:
            context['display_sidenav'] = True

        context['widgets'][widget_type.__name__][widget.name] = widget.get_context()

    @staticmethod
    def has_widget_type(context: Dict[str, Any], widget_type: Type[Widget]) -> bool:
        """
        Checks if the context dictionary contains at least one widget of the specified type.

        :param context: Context dictionary to check.
        :type context: Dict[str, Any]
        :param widget_type: Widget type to check for.
        :type widget_type: Type[Widget]

        :return: `True` if the context dictionary contains at least one widget of the specified
            type, `False` otherwise.
        :rtype: bool

        :raises WidgetException: If the widget type is not recognized.
        """
        if widget_type not in BaCa2ContextMixin.WIDGET_TYPES:
            widget_type = BaCa2ContextMixin.get_type(widget_type)
        if not widget_type:
            raise BaCa2ContextMixin.WidgetException(f'Widget type not recognized: {widget_type}.')
        if context['widgets'][widget_type.__name__]:
            return True
        return False

    @staticmethod
    def has_widget(context: Dict[str, Any], widget_type: Type[Widget], widget_name: str) -> bool:
        """
        Checks if the context dictionary contains a widget of the specified type and name.

        :param context: Context dictionary to check.
        :type context: Dict[str, Any]
        :param widget_type: Widget type to check for.
        :type widget_type: Type[Widget]
        :param widget_name: Widget name to check for.
        :type widget_name: str

        :return: `True` if the context dictionary contains a widget of the specified type and name,
            `False` otherwise.
        :rtype: bool

        :raises WidgetException: If the widget type is not recognized.
        """
        if widget_type not in BaCa2ContextMixin.WIDGET_TYPES:
            raise BaCa2ContextMixin.WidgetException(f'Widget type not recognized: {widget_type}.')
        if context['widgets'][widget_type.__name__].get(widget_name, None):
            return True
        return False

    @staticmethod
    def get_type(widget_cls: Type[Widget]) -> Type[Widget] | None:
        """
        Returns the type of given widget class if it is recognized, `None` otherwise.

        :param widget_cls: Widget class to check.
        :type widget_cls: Type[Widget]

        :return: Type of the widget class if recognized, `None` otherwise.
        :rtype: Type[Widget] | None
        """
        for widget_type in BaCa2ContextMixin.WIDGET_TYPES:
            if issubclass(widget_cls, widget_type):
                return widget_type
        return None


class BaCa2LoggedInView(LoginRequiredMixin, BaCa2ContextMixin, TemplateView):
    """
    Base view for all views which require the user to be logged in. Inherits from BaCa2ContextMixin
    providing a navbar widget and a preliminary setup for the context dictionary.
    """

    #: Baca2LoggedInView is a base, abstract class and as such does not have a template. All
    #: subclasses should provide their own template.
    template_name = None


class FieldValidationView(LoginRequiredMixin, View):
    """
    View used for live field validation. Its :meth:`get` method is called whenever the value of a
    field with live validation enabled changes. The method returns a JSON response containing the
    validation status of the field and any potential error messages to be displayed.

    See also:
        - :meth:`widgets.forms.fields.validation.get_field_validation_status`
        - :class:`widgets.forms.base.FormWidget`
    """

    class ValidationRequestException(Exception):
        """
        Exception raised when a validation request does not contain the required data.
        """
        pass

    @staticmethod
    def get(request, *args, **kwargs) -> JsonResponse:
        """
        Parses the request for the required data and returns a JSON response containing the
        validation status of the field and any potential error messages to be displayed.

        :return: JSON response with validation status and error messages.
        :rtype: JsonResponse
        :raises ValidationRequestException: If the request does not contain the required data.
        """

BaCa2/templates/util/baca2_logo.html
<svg class="baca2-logo logo-horizontal" width="820" height="210" viewBox="0 0 820 210"
     style="fill-rule:evenodd;
            clip-rule:evenodd;
            stroke-linejoin:round;
            stroke-miterlimit:2;">
    <g id="triangle">
        <path class="logo-small-triangle"
              d="M203.615,157.469l-30.305,52.49l60.61,-0l-30.305,-52.49Z"
              fill="#fc2d63"></path>
        <path class="logo-medium-triangle"
              d="M264.225,157.469l-30.305,52.49l60.61,-0l-30.305,-52.49Z"
              fill="#d3cabd"></path>
        <path class="logo-medium-triangle"
              d="M233.92,104.979l-30.305,52.49l60.61,0l-30.305,-52.49Z"
              fill="#d3cabd"></path>
        <path class="logo-large-triangle"
              d="M355.14,104.979l-60.61,104.98l121.22,-0l-60.61,-104.98Z"
              fill="#1cd9d6"></path>
        <path class="logo-large-triangle"
              d="M294.53,0l-60.61,104.979l121.22,0l-60.61,-104.979Z"
              fill="#1cd9d6"></path>
    </g>
    <path id="A" class="logo-stroke"
          d="M610.041,209.959l104.98,-209.959l104.979,209.959l-11.18,-0l-50,-100c-15.884,-0 -87.599,-0 -87.598,-0l-50,100l-11.181,-0Zm143.779,-110l-38.799,-77.598l-38.799,77.598l77.598,-0Z"
          fill="white"></path>
    <path id="C" class="logo-stroke"
          d="M582.155,172.196l7.071,7.071c-40.978,40.977 -107.515,40.977 -148.493,-0c-40.977,-40.978 -40.977,-107.515 0,-148.493c40.978,-40.977 107.515,-40.977 148.493,0l-7.071,7.071c-37.075,-37.075 -97.276,-37.075 -134.351,0c-37.075,37.075 -37.075,97.276 0,134.351c37.075,37.075 97.276,37.075 134.351,-0Z"
          fill="white"></path>
    <path id="B" class="logo-stroke"
          d="M115,210l-115,0l0,-210l115,0c30.355,0 55,24.645 55,55c-0,22.174 -13.15,41.301 -32.071,50c18.921,8.699 32.071,27.826 32.071,50c0,30.355 -24.645,55 -55,55Zm-105,-110l105,0c24.836,0 45,-20.164 45,-45c-0,-24.836 -20.164,-45 -45,-45c0,0 -105,0 -105,-0l0,90Zm105,10l-105,0l0,90l105,0c24.836,0 45,-20.164 45,-45c-0,-24.836 -20.164,-45 -45,-45Z"
          fill="white"></path>
</svg>

<svg class="baca2-logo logo-square" width="500" height="500" viewBox="0 0 500 500"
     style="fill-rule:evenodd;
            clip-rule:evenodd;
            stroke-linejoin:round;
            stroke-miterlimit:2;">
    <g id="triangle">
        <path d="M264.065,182.49l-30.305,52.489l60.61,0l-30.305,-52.489Z"
              fill="#fc2d63"></path>
        <path d="M324.674,182.49l-30.304,52.489l60.609,0l-30.305,-52.489Z"
              fill="#d3cabd"></path>
        <path d="M294.37,130l-30.305,52.49l60.609,-0l-30.304,-52.49Z"
              fill="#d3cabd"></path>
        <path d="M415.589,130l-60.61,104.979l121.22,0l-60.61,-104.979Z"
              fill="#1cd9d6"></path>
        <path d="M354.979,25.021l-60.609,104.979l121.219,0l-60.61,-104.979Z"
              fill="#1cd9d6"></path>
    </g>
    <path id="frame" class="logo-stroke"
          d="M500,500l-500,-0l-0,-500l500,0l0,500Zm-10,-490l-480,-0l-0,480l480,0l0,-480Z"
          fill="white"></path>
    <path id="A" class="logo-stroke"
          d="M250,474.979l104.979,-209.958l104.98,209.958l-11.181,0l-50,-100c-15.883,0 -87.598,0 -87.598,0l-50,100l-11.18,0Zm143.778,-110l-38.799,-77.598l-38.799,77.598l77.598,0Z"
          fill="white"></path>
    <path id="C" class="logo-stroke"
          d="M212.542,437.175l7.071,7.071c-40.978,40.978 -107.515,40.978 -148.493,0c-40.977,-40.977 -40.977,-107.515 0,-148.492c40.978,-40.978 107.515,-40.978 148.493,-0l-7.071,7.071c-37.075,-37.075 -97.276,-37.075 -134.351,-0c-37.075,37.075 -37.075,97.275 0,134.35c37.075,37.075 97.276,37.075 134.351,0Z"
          fill="white"></path>
    <path id="B" class="logo-stroke"
          d="M160,235l-115,0l0,-210l115,-0c30.355,-0 55,24.645 55,55c-0,22.174 -13.15,41.301 -32.071,50c18.921,8.699 32.071,27.826 32.071,50c0,30.355 -24.645,55 -55,55Zm-105,-110l105,0c24.836,0 45,-20.164 45,-45c-0,-24.836 -20.164,-45 -45,-45c0,0 -105,0 -105,-0l0,90Zm105,10l-105,0l0,90l105,0c24.836,0 45,-20.164 45,-45c-0,-24.836 -20.164,-45 -45,-45Z"
          fill="white"></path>
</svg>

<svg class="baca2-logo logo-icon" width="243" height="210" viewBox="0 0 243 210"
     style="fill-rule:evenodd;
            clip-rule:evenodd;
            stroke-linejoin:round;
            stroke-miterlimit:2;">
    <g id="triangle">
        <path d="M30.305,157.469l-30.305,52.49l60.61,-0l-30.305,-52.49Z"
              fill="#fc2d63"></path>
        <path d="M90.915,157.469l-30.305,52.49l60.61,-0l-30.305,-52.49Z"
              fill="#d3cabd"></path>
        <path d="M60.61,104.979l-30.305,52.49l60.61,0l-30.305,-52.49Z"
              fill="#d3cabd"></path>
        <path d="M181.83,104.979l-60.61,104.98l121.219,-0l-60.609,-104.98Z"
              fill="#1cd9d6"></path>
        <path d="M121.22,0l-60.61,104.979l121.22,0l-60.61,-104.979Z"
              fill="#1cd9d6"></path>
    </g>
</svg>

BaCa2/templates/util/theme_button.html
{% load static %}
<script src="{% static 'js/themes.js' %}"></script>

<form>
    {% csrf_token %}
    <div class="theme-button d-flex">
        <a href="#"
           onclick="switchTheme(post_url='{% url 'main:change-theme' %}', csrf_token='{{ csrf_token }}')">

            <div class="d-flex icon-wrapper icon-m" id="moon">
                {% include "icons/moon.svg" %}
            </div>
            <div class="d-flex icon-wrapper icon-m" id="sun">
                {% include "icons/sun.svg" %}
            </div>
        </a>
    </div>
</form>

BaCa2/templates/util/theme_switch.html
{% load static %}
<script src="{% static 'js/themes.js' %}"></script>

<div class="theme-switch d-flex">
    <div class="d-flex flex-row justify-content-center align-items-center">
        <div class="col-auto pb-1">
            <div class="icon-wrapper icon-s">
                {% include "icons/moon.svg" %}
            </div>
        </div>
        <div class="col-auto ms-2">
            <form>
                {% csrf_token %}
                <div class="form-check form-switch">
                    <input
                        class="form-check-input p-2"
                        type="checkbox"
                        role="switch"
                        onclick="switchTheme(
                            post_url='{% url 'main:change-theme' %}',
                            csrf_token='{{ csrf_token }}')"
                        {% if data_bs_theme == "light" %}
                            checked
                        {% endif %}/>
                </div>
            </form>
        </div>
        <div class="col-auto pb-1">
            <div class="icon-wrapper icon-s">
                {% include "icons/sun.svg" %}
            </div>
        </div>
    </div>
</div>